save-position-on-quit
vo=gpu
# video-sync=display-resample
# interpolation=yes
# tscale=oversample
# sws-fast=yes
profile=fast
save-watch-history

sub-font-size=28
sub-color="#ddffffff"
sub-border-style=opaque-box
sub-outline-color="#88000000"
sub-margin-y=10
sub-delay=-0.4
