require("gruvbox").setup({
	terminal_colors = false, -- add neovim terminal colors
	undercurl = false,
	underline = true,
	bold = true,
	italic = {
		strings = false,
		emphasis = true,
		comments = true,
		operators = false,
		folds = false,
	},
	strikethrough = false,
	invert_selection = false,
	inverse = true, -- invert background for search, diffs, statuslines and errors
	contrast = "hard", -- can be "hard", "soft" or empty string
	overrides = {
		ColorColumn = { bg = "#171717" },
		SignColumn = { bg = "#070505" },
		NonText = { fg = "#191716" }, -- indentline
		FloatBorder = { bg = "none", fg = "#ebdbb2" },
		NormalFloat = { bg = "none" },
		Whitespace = { fg = "#191716" },
		IblScope = { fg = "#7c6f64" },
		Normal = { bg = "#070505" },
		WinSeparator = { bg = "#070505", fg = "#bfb2a5" },
		GruvboxYellowSign = { bg = "#070505" },
		GruvboxRedSign = { bg = "#070505" },
		GruvboxBlueSign = { bg = "#070505" },
		RenderMarkdownCode = { bg = "#312e2c" },
		GruvboxRedUnderline = { underdotted = true },
		GruvboxAquaUnderline = { underline = true },
		GruvboxBlueUnderline = { underline = true },
		GruvboxGreenUnderline = { underline = true },
		GruvboxOrangeUnderline = { underline = true },
		GruvboxYellowUnderline = { underline = true },
		GruvboxPurpleUnderline = { underline = true },
		DapUIStop = { bg = "#070505" },
		DapUIStepInto = { bg = "#070505" },
		DapUIStepOver = { bg = "#070505" },
		DapUIStepOut = { bg = "#070505" },
		DapUIRestart = { bg = "#070505" },
		DapUIStepBack = { bg = "#070505" },
		DapUIPlayPause = { bg = "#070505" },
		StatusLine = { bg = "#a89984", fg = "#7c6f64" },
		StatusLineNC = { bg = "#32302f", fg = "#7c6f64" },
		TreesitterContext = { bg = "#32302f", fg = "#7c6f64" },
		TreesitterContextLineNumber = { bg = "#32302f", fg = "#7c6f64" },
		TreesitterContextBottom = { underline = true, sp = "#7c6f64" },
	},
})
vim.cmd("colorscheme gruvbox")
