# █ █ █▄█ █▀█ █▀█ █   █▀█ █▀▀ █▄▀
# █▀█  █  █▀▀ █▀▄ █▄▄ █▄█ █▄▄ █ █

$mpris_art = /tmp/hyde-mpris.png
$artfile = /tmp/hyde-mpris-blurred.png
# $wall = $HOME/.cache/hyde/wall.set

# Music blur div
shape {
    monitor =
    size = 440, 110
    color = white
    rounding = 20
    rotate = 0
    position = 30, -310
    halign = center
    valign = center
    zindex = 1
}

# Music Album Art
image {
    monitor =
    path = $mpris_art
    size = 80
    rounding = 0
    rotate = 0
    reload_time = 100
    reload_cmd = 
    position = -130, -310
    halign = center
    valign = center
    zindex = 5
}

# PLAYER TITLE
label {
    monitor =
    text = cmd[update:1000] echo "$($music --title)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 12
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 880, -310
    halign = left
    valign = center
    zindex = 5
}

# PLAYER LENGTH
label {
    monitor =
    text = cmd[update:1000] $music --length
    color = rgba(255, 255, 255, 1)
    font_size = 11
    font_family = JetBrains Mono Nerd Font Mono
    position = -730, -332
    halign = right
    valign = center
    zindex = 5
}

# PLAYER STATUS
label {
    monitor =
    text = cmd[update:1000] echo "$($music --status)"
    color = rgba(255, 255, 255, 1)
    font_size = 14
    font_family = JetBrains Mono Nerd Font Mono 
    position = -730, -310
    halign = right
    valign = center
    zindex = 5
}

# PLAYER SOURCE
label {
    monitor =
    text = cmd[update:1000] echo "$($music --source)"
    color = rgba(255, 255, 255, 0.6)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono 
    position = 880, -280
    halign = left
    valign = center
    zindex = 5
}

# PLAYER ARTIST
label {
    monitor =
    text = cmd[update:1000] echo "$($music --artist)"
    color = rgba(255, 255, 255, 0.8)
    font_size = 10
    font_family = JetBrains Mono Nerd Font Mono ExtraBold
    position = 880, -330
    halign = left
    valign = center
    zindex = 5
}
