#!/bin/bash
i3-msg -t subscribe -m '{"type":"workspace"}' |
while read -r _; do
    workspaces_info=$(i3-msg -t get_workspaces)
    active_workspaces=$(echo "$workspaces_info" | jq --unbuffered -r '[.[] | .name] | join(" ")')
    echo "$active_workspaces"
done
# while true; do
#     wmctrl -d | awk -F' ' '{ if ($2=="*") print $1+1; }';
#     sleep 0.2;
# done
