#!/bin/bash

handle() {
    ws_list=$(hyprctl clients\
        | grep -E "^\s*workspace:"\
        | sed "s/.*workspace: //"\
        | sed "s/ (.*)//")
    echo $ws_list
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle; done
