#!/bin/bash

COMMAND="amixer sget Master"

sound_on="$($COMMAND | grep -m 1 -E -i -o '\[on\]')"

volume_level=$($COMMAND | grep -m 1 -E -i -o '\[[0-9]*%\]' | grep -E -o -i '[0-9]*')

[[ $sound_on == "[on]" ]] && echo $volume_level || echo "0"
