#!/bin/bash

_MEM_AVAIL=`cat /proc/meminfo | awk -F ":" 'NR==3{print $2;}'`
_MEM_AVAIL=${_MEM_AVAIL%\ kB}
_MEM_TOTAL=`cat /proc/meminfo | awk -F ":" 'NR==1{print $2;}'` 
_MEM_TOTAL=${_MEM_TOTAL%\ kB}
_MEM_RATIO=$((6-6*_MEM_AVAIL/_MEM_TOTAL))

for((i=0; i<_MEM_RATIO; i++)); do
	echo -n "▮"
done
for((i=0; i<6-_MEM_RATIO; i++)); do
	echo -n "▯"
done

printf " %.1fG/%.1fG" $((_MEM_TOTAL-_MEM_AVAIL))e-6 $((_MEM_TOTAL))e-6
