return {
    "folke/snacks.nvim",
    priority = 1000,
    lazy = false,
    opts = {
        animate = { enabled = false },
        bigfile = { enabled = true },
        bufdelete = { enabled = false },
        dashboard = { enabled = false },
        debug = { enabled = false },
        dim = { enabled = false },
        git = { enabled = false },
        gitbrowse = { enabled = false },
        indent = { enabled = false },
        input = { enabled = false },
        lazygit = { enabled = true },
        notifier = { enabled = false },
        notify = { enabled = false },
        profiler = { enabled = false },
        quickfile = { enabled = false },
        rename = { enabled = false },
        scope = { enabled = false },
        scratch = { enabled = false },
        scroll = { enabled = false },
        statuscolumn = { enabled = true },
        terminal = { enabled = true },
        toggle = { enabled = false },
        util = { enabled = true },
        win = { enabled = true },
        words = { enabled = false },
        zen = { enabled = false },
    },
    init = function()
        vim.cmd([[command LazyGitLog lua require"snacks".lazygit.log()]])
    end,
}
